spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mohe_db}
    username: ${DB_USERNAME:mohe_user}
    password: ${DB_PASSWORD:mohe_password}

  batch:
    job:
      enabled: false

mohe:
  image:
    storage-path: ${IMAGE_STORAGE_PATH:./images}
    server-url: ${IMAGE_SERVER_URL:http://localhost:8080}
    use-remote: ${IMAGE_USE_REMOTE:false}
  image-processor:
    url: ${IMAGE_PROCESSOR_URL:http://100.99.236.50:5200}

crawler:
  base-url: ${CRAWLER_SERVER_URL:http://localhost:4000}

embedding:
  service:
    url: ${EMBEDDING_SERVICE_URL:http://localhost:2000}
